#!/usr/bin/env bash
# Serialize collector, Cron, changedetection, repair and test jobs.
#
# A running job is never killed to make room for another job. Lower-priority
# requests are written as small executable job files and drained, highest
# priority first, when the active job exits.
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" && pwd)"
# shellcheck source=../../lib/env.sh
source "$SCRIPT_DIR/../../lib/env.sh"
cd "$APP_ROOT"

LOCK_FILE="$PC_QUEUE_DIR/priority-run.lock"
WAIT_LOCK_FILE="$PC_QUEUE_DIR/priority-run-wait.lock"
STATE_FILE="$PC_QUEUE_DIR/priority-run.state"
PENDING_DIR="$PC_QUEUE_DIR/priority-pending"
LOG_FILE="$PC_LOG_DIR/priority-run.log"
SELF="$SCRIPT_DIR/125-run-priority.sh"

mkdir -p "$PENDING_DIR" "$PC_LOG_DIR"

timestamp() { date '+%Y-%m-%d %H:%M:%S'; }
quote_value() { printf "%s" "$1" | sed "s/'/'\\\\''/g"; }
safe_name() { printf "%s" "$1" | tr -c '[:alnum:]_.-' '_'; }

priority_for() {
  case "${1,,}" in
    update|migration) echo 100 ;;
    repair) echo 90 ;;
    test) echo 80 ;;
    manual) echo 60 ;;
    cron) echo 40 ;;
    changedetection|webhook) echo 20 ;;
    *) echo 30 ;;
  esac
}

write_state() {
  local phase="$1" status="$2" source="$3" priority="$4" label="$5" pid="$6" message="$7"
  local tmp="${STATE_FILE}.tmp"
  {
    echo "PHASE='$(quote_value "$phase")'"
    echo "STATUS='$(quote_value "$status")'"
    echo "SOURCE='$(quote_value "$source")'"
    echo "PRIORITY='$(quote_value "$priority")'"
    echo "LABEL='$(quote_value "$label")'"
    echo "PID='$(quote_value "$pid")'"
    echo "MESSAGE='$(quote_value "$message")'"
    echo "UPDATED_AT='$(timestamp)'"
  } > "$tmp"
  mv "$tmp" "$STATE_FILE"
}

clear_state() { rm -f "$STATE_FILE"; }
stop_requested() { [ -f "$PC_QUEUE_DIR/run_all_stop_no_resume.flag" ]; }
discard_pending_after_stop() {
  rm -f "$PENDING_DIR"/*.job 2>/dev/null || true
  log "discarded pending priority jobs because a manual no-resume stop was requested"
}

log() {
  echo "$(timestamp) | priority-run | $*" >> "$LOG_FILE"
}

external_busy() {
  [ "${PC_PRIORITY_SKIP_PROCESS_CHECK:-0}" = "1" ] && return 1
  # These patterns intentionally use a bracketed first character so pgrep does
  # not match the inspection command itself. The priority wrapper bypasses this
  # check for child steps owned by the active collector.
  pgrep -f '[r]un-worker.sh|[0]70-test-zone.py|[0]50-repair-missing-deadlines.py|[u]pdate-local-copy.sh|[0]03-update-loader.py|[0]60-build-calendar.py|[0]40-build-detail-views.py' >/dev/null 2>&1
}

write_job() {
  local source="$1" priority="$2" label="$3" coalesce="$4"
  shift 4
  local key file tmp command_text
  key="$(safe_name "$coalesce")"
  if [ -n "$key" ] && find "$PENDING_DIR" -maxdepth 1 -type f -name "*-${key}.job" -print -quit | grep -q .; then
    log "coalesced pending request source=$source key=$coalesce"
    return 2
  fi
  file="$PENDING_DIR/p$((999 - priority))-$(date +%s%N)-$$-${key:-job}.job"
  tmp="${file}.tmp"
  printf -v command_text '%q ' "$@"
  {
    echo "SOURCE='$(quote_value "$source")'"
    echo "PRIORITY='$(quote_value "$priority")'"
    echo "LABEL='$(quote_value "$label")'"
    echo "COALESCE_KEY='$(quote_value "$coalesce")'"
    echo "COMMAND=($command_text)"
  } > "$tmp"
  mv "$tmp" "$file"
  log "queued source=$source priority=$priority label=$label key=$coalesce file=$(basename "$file")"
  return 0
}

start_waiter() {
  # Only one waiter is needed when an old/direct process was already running
  # before the priority wrapper was installed.
  (
    exec 8>"$WAIT_LOCK_FILE"
    flock -n 8 || exit 0
    nohup "$SELF" --drain >/dev/null 2>&1 &
  ) >/dev/null 2>&1
}

run_job() {
  local source="$1" priority="$2" label="$3"
  local run_type
  shift 3
  case "${source,,}" in
    test) run_type="TEST" ;;
    repair) run_type="REPAIR" ;;
    update|migration) run_type="UPDATE" ;;
    maintenance) run_type="MAINTENANCE" ;;
    *) run_type="COLLECTOR" ;;
  esac
  write_state "RUNNING" "RUNNING" "$source" "$priority" "$label" "$$" "Running $label"
  log "started source=$source priority=$priority label=$label pid=$$"
  PC_PRIORITY_ACTIVE=1 PC_PRIORITY_SOURCE="$source" PC_PRIORITY_PRIORITY="$priority" \
    PC_PRIORITY_LABEL="$label" PC_RUN_TYPE="$run_type" PC_RUN_SOURCE="$source" \
    PC_RUN_TRIGGER="priority-queue" "$@"
  local rc=$?
  log "finished source=$source priority=$priority label=$label exit=$rc"
  clear_state
  return "$rc"
}

drain_pending() {
  local job source priority label coalesce rc=0
  while true; do
    if stop_requested; then
      discard_pending_after_stop
      break
    fi
    job="$(find "$PENDING_DIR" -maxdepth 1 -type f -name '*.job' -printf '%p\n' 2>/dev/null | sort | head -n1)"
    [ -n "$job" ] || break
    # The file is generated by this script and contains only shell-quoted
    # assignments plus a quoted command array.
    unset SOURCE PRIORITY LABEL COALESCE_KEY COMMAND
    # shellcheck disable=SC1090
    . "$job"
    rm -f "$job"
    source="${SOURCE:-other}"
    priority="${PRIORITY:-$(priority_for "$source")}";
    label="${LABEL:-$source}"
    run_job "$source" "$priority" "$label" "${COMMAND[@]}" || rc=$?
  done
  return "$rc"
}

drain() {
  exec 9>"$LOCK_FILE"
  flock -n 9 || exit 0
  while external_busy; do
    write_state "WAITING" "QUEUED" "external" "0" "Existing process" "-" "Waiting for the active process to finish before resuming queued work."
    sleep 2
  done
  drain_pending
  clear_state
}

if [ "${1:-}" = "--drain" ]; then
  drain
  exit $?
fi

SOURCE="${1:-other}"
PRIORITY="${2:-$(priority_for "$SOURCE")}"
COALESCE_KEY="${3:-$SOURCE}"
shift 3 || true
if [ "${1:-}" != "--" ] || [ "$#" -lt 2 ]; then
  echo "Usage: 125-run-priority.sh SOURCE [PRIORITY] [COALESCE_KEY] -- COMMAND [ARGS...]" >&2
  exit 2
fi
shift
LABEL="${PC_PRIORITY_LABEL:-$SOURCE}"

if [ "${PC_PRIORITY_ACTIVE:-0}" != "1" ] && external_busy; then
  write_job "$SOURCE" "$PRIORITY" "$LABEL" "$COALESCE_KEY" "$@"
  start_waiter
  echo "Queued: $LABEL (priority $PRIORITY); active work will finish first."
  exit 0
fi

exec 9>"$LOCK_FILE"
if ! flock -n 9; then
  write_job "$SOURCE" "$PRIORITY" "$LABEL" "$COALESCE_KEY" "$@"
  echo "Queued: $LABEL (priority $PRIORITY); it will resume after the active job."
  exit 0
fi

run_job "$SOURCE" "$PRIORITY" "$LABEL" "$@"
RC=$?
if stop_requested; then
  discard_pending_after_stop
  clear_state
  exit "$RC"
fi
drain_pending
clear_state
exit "$RC"
