"""Shared native window icons for PanamaCompra Tk applications.

The desktop launchers use SVG files, but Tk cannot reliably load SVG on every
supported Linux installation.  These small icons are drawn directly into a
``PhotoImage`` so the taskbar/dock receives ``_NET_WM_ICON`` without Pillow or
any other optional dependency.
"""
from __future__ import annotations

import math
import tkinter as tk
from typing import Any


WINDOW_CLASSES = {
    # Tk normalizes className capitalization in WM_CLASS. Keep these values
    # identical to the StartupWMClass entries generated by the installer.
    "monitor": "Panamacompramonitor",
    "timer": "Panamacompratimer",
    "updater": "Panamacompraupdater",
}


def window_class(kind: str) -> str:
    """Return the stable WM class used by the matching desktop launcher."""
    return WINDOW_CLASSES.get(kind, "PanamaCompra")


def _rect(image: tk.PhotoImage, color: str, x1: int, y1: int, x2: int, y2: int) -> None:
    image.put(color, to=(x1, y1, x2, y2))


def _circle(image: tk.PhotoImage, color: str, cx: int, cy: int, radius: int) -> None:
    for y in range(cy - radius, cy + radius + 1):
        half = int(math.sqrt(max(0, radius * radius - (y - cy) ** 2)))
        image.put(color, to=(cx - half, y, cx + half + 1, y + 1))


def build_window_icon(master: Any, kind: str, size: int = 64) -> tk.PhotoImage:
    """Build a dependency-free taskbar icon for a Tk root window."""
    image = tk.PhotoImage(master=master, width=size, height=size)
    _rect(image, "#0f172a", 0, 0, size, size)

    if kind == "timer":
        _circle(image, "#38bdf8", 32, 32, 24)
        _circle(image, "#1e293b", 32, 32, 19)
        _rect(image, "#fbbf24", 30, 16, 34, 34)
        _rect(image, "#fbbf24", 32, 30, 47, 34)
        _circle(image, "#22c55e", 32, 32, 4)
    elif kind == "updater":
        _rect(image, "#111827", 10, 12, 54, 50)
        _rect(image, "#38bdf8", 14, 16, 50, 46)
        _rect(image, "#111827", 18, 20, 46, 42)
        _rect(image, "#fbbf24", 29, 19, 35, 36)
        _rect(image, "#fbbf24", 23, 30, 41, 36)
        _rect(image, "#22c55e", 20, 48, 44, 54)
    else:
        _rect(image, "#38bdf8", 8, 11, 56, 48)
        _rect(image, "#111827", 13, 16, 51, 43)
        _rect(image, "#22c55e", 18, 31, 25, 36)
        _rect(image, "#22c55e", 24, 24, 30, 36)
        _rect(image, "#22c55e", 29, 31, 37, 36)
        _rect(image, "#22c55e", 36, 20, 42, 36)
        _rect(image, "#22c55e", 41, 31, 47, 36)
        _rect(image, "#94a3b8", 29, 48, 35, 55)
        _rect(image, "#94a3b8", 20, 54, 44, 59)
    return image


def apply_window_icon(root: Any, kind: str) -> tk.PhotoImage:
    """Set and retain the icon for a root and all of its future child windows."""
    icon = build_window_icon(root, kind)
    root.iconphoto(True, icon)
    # Tk images disappear when Python releases the last reference.
    root._panamacompra_window_icon = icon
    return icon
